### ISSUE TITLE
Döviz bilgilerinin eklenmesi

### ISSUE THREAD

**Issue by hmert** [naynco/nayn.cli#1]
Kaynak olarak sorun olmayacak bir yerden içeriğin sağlanarak cli içinde gösterilmesi güzel olabilir.

**Comment by fakturk** [comment]
doviz.com uzerinden ekleyebiliriz, ben dolar i doviz.com uzerinden ceken bir parca go kodu yazmistim https://github.com/fakturk/kacdolar/blob/master/dolar.go#L56 bunu diger doviz turlerine de uyarlayabilirim, ya da merkez bankasi uzerinden cekebiliriz https://www.tcmb.gov.tr/kurlar/today.xml

**Comment by hmert** [comment]
65206a78ec0d847155f7505574576d5a9ab571d2 is done
