### ISSUE TITLE
README file Installation Instructions

### ISSUE THREAD

**Issue by lahmacun** [naynco/nayn.cli#3]
I don't have any knowledge about how to compile the code. It would be great if installation instructions added to readme.

Thanks a lot.

**Comment by hmert** [comment]
@lahmacun We have releases. But readme will have the links. 🖖 
 
 https://github.com/naynco/nayn.cli/releases/tag/v1.0.4

**Comment by lahmacun** [comment]
Sorry about that, didn't notice releases. Thx
