### ISSUE TITLE
item.GUID yerine item.Link olabilir mi?

### ISSUE THREAD

**Issue by aligoren** [naynco/nayn.cli#5]
Selam. Asagidaki kodda item.GUID alinarak haber url'i basiliyor sanirim.

https://github.com/naynco/nayn.cli/blob/326fe38be72139ccd8aa270e858292cb7672fe77/main.go#L88

Yani alinan yeri;

```xml
<guid isPermaLink="false">https://nayn.co/?p=223571</guid>
```

Bunun yerine;
 
```xml
<link>https://nayn.co/uber-kasim-ayinda-otonom-araclari-yeni-bir-sehirde-test-edecek/</link>
```

Bu kisim alinsa terminal gorunumu icin kotu mu olurdu?

**Comment by hmert** [comment]
@aligoren selam, evet. Terminalde deneyebilirsin istersen. Bizim başlıklar uzun olduğu için aşağıya doğru kaçıyor maalesef.

**Comment by aligoren** [comment]
Hmm. Acaba terminal URL tasiyan bir sistem var mi. Tab gibi dolasilacak yani. O da guzel olabilirdi.

Ben kendime size soyledigim gibi yaptim ama basliklar uzerinde enter'a basilinca direkt tarayicida acilabilir olusu da guzel olurdu.

**Comment by hmert** [comment]
![image](https://user-images.githubusercontent.com/182906/65420424-cbfdf180-de09-11e9-8db4-eadfd9f2ca1c.png)
şöyle bir şey var mac terminalde. Cursor ile yürüyen bir şey yapılabilir belki.

**Comment by aligoren** [comment]
Belki de benim dedigim daha cok keyboard navigation tarzi bir seydi.

**Comment by hmert** [comment]
https://github.com/manifoldco/promptui şu güzel görünüyor ancak zamanlama olarak ben diğerlerine vakit ayıracağım :) eğer PR gönderirsen değerlendiririz
